// <auto-generated />
using System;
using CrudTreino.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudTreino.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210622172846_DependentesModel")]
    partial class DependentesModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrudTreino.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("dependenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pessoa");
                });

            modelBuilder.Entity("CrudTreino.Models.Dependente", b =>
                {
                    b.HasBaseType("CrudTreino.Models.Pessoa");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("int");

                    b.HasIndex("ResponsavelId");

                    b.HasDiscriminator().HasValue("Dependente");
                });

            modelBuilder.Entity("CrudTreino.Models.Dependente", b =>
                {
                    b.HasOne("CrudTreino.Models.Pessoa", "Responsavel")
                        .WithMany("Dependentes")
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("CrudTreino.Models.Pessoa", b =>
                {
                    b.Navigation("Dependentes");
                });
#pragma warning restore 612, 618
        }
    }
}
